### ISSUE TITLE
Make version compatible with .net Framework 0.4.0

### ISSUE THREAD

**Issue by domenicw1** [LunaSoftoffical/LS-DOS-2017#2]
because of it needs 0.4.2 i cant use it on vista

**Comment by ghost** [comment]
You should be able to. If you have SP2 you can get the latest .net framework. https://www.microsoft.com/en-us/download/details.aspx?id=42643

**Comment by domenicw1** [comment]
That dosent works for me , i have ,net framework 4.5.1 and if try to download 4.2 it says i alredy have an higher version of ,net

**Comment by domenicw1** [comment]
![image](https://cloud.githubusercontent.com/assets/22521667/23139645/c411ed86-f7ad-11e6-9eef-a09eae668e0d.png)

**Comment by ghost** [comment]
Well, you do have a higher version of .NET

**Comment by ghost** [comment]
Launch the program and screenshot the error for me.

**Comment by domenicw1** [comment]
![image](https://cloud.githubusercontent.com/assets/22521667/23139672/e34b9d96-f7ad-11e6-8157-9fb57f040557.png)

**Comment by ghost** [comment]
Click yes, You have 4.5.1, not 4.5.2.

**Comment by domenicw1** [comment]
If i click yes it gives me a link of 4.6.2 which isnt supported on vista

**Comment by ghost** [comment]
Try downloading this. https://www.microsoft.com/en-us/download/details.aspx?id=42643

**Comment by domenicw1** [comment]
ok thanks

**Comment by ghost** [comment]
No problem. Let me know if the issue persists.

**Comment by ghost** [comment]
@LunaSoftoffical Close this
