### ISSUE TITLE
Wrong Spelling (GS-DOS)

### ISSUE THREAD

**Issue by domenicw1** [LunaSoftoffical/LS-DOS-2017#5]
The title of  the program is GS-DOS while its showing:
Starting LS-DOS
![image](https://cloud.githubusercontent.com/assets/22521667/23140720/81b36cfc-f7b3-11e6-8bc8-d65b3a88bb46.png)

**Comment by ghost** [comment]
This has already been fixed in a commit by me. I am waiting on @LunaSoftoffical to merge my pull requests.

**Comment by domenicw1** [comment]
ok

**Comment by LunaSoftoffical** [comment]
It has been fixed.
